name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      - name: Install dependencies
        run: npm install

      - name: Install Android platform
        run: npm install @capacitor/android

      - name: Build web app
        run: npm run build

      - name: Initialize Capacitor
        run: |
          npx cap init MyApp com.example.myapp
          npx cap add android

      - name: Copy web assets to Android project
        run: npx cap copy android
