name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: |
          mkdir -p android/app/src/main/assets
          cp index.html android/app/src/main/assets/
          echo "APK build placeholder"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: gposhlina-calculator.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
